# Generated by Django 6.0.2 on 2026-06-28 03:42

import nexo.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenantcompanyaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=nexo.upload_paths.TenantPath('logo', self_is_tenant=True), verbose_name='Logo da empresa'),
        ),
    ]
