# Generated by Django 6.0.5 on 2026-06-17 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_backfill_personal_tenants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('investment_type', models.CharField(choices=[('stocks', 'Ações'), ('fii', 'FII'), ('fixed_income', 'Renda Fixa'), ('crypto', 'Cripto'), ('savings', 'Poupança'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo')),
                ('broker', models.CharField(blank=True, max_length=120, verbose_name='Corretora / Banco')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ('-is_active', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InvestmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('deposit', 'Aporte'), ('withdrawal', 'Resgate'), ('dividend', 'Dividendo'), ('yield', 'Rendimento')], default='deposit', max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='investments.investment', verbose_name='Investimento')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_entries', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lancamento de investimento',
                'verbose_name_plural': 'Lancamentos de investimento',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['tenant', 'date'], name='investments_tenant__9601d0_idx'), models.Index(fields=['investment', 'date'], name='investments_investm_fbea90_idx')],
            },
        ),
    ]
