# Generated by Django 6.0.5 on 2026-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="investment_type",
            field=models.CharField(
                choices=[
                    ("stocks", "Ações"),
                    ("fii", "FII"),
                    ("fixed_income", "Renda Fixa"),
                    ("crypto", "Cripto"),
                    ("savings", "Poupança"),
                    ("emergency", "Reserva de Emergência"),
                    ("other", "Outro"),
                ],
                default="other",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
