# Generated by Django 6.0.5 on 2026-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("issued", "Emitida"),
                    ("paid", "Paga"),
                    ("cancelled", "Cancelada"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
