# Generated by Django 6.0.5 on 2026-06-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_cardmonthlylimit"),
        ("invoices", "0003_client_phone_invoice_client_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="expected_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Conta onde a receita deverá ser lançada ao confirmar o pagamento.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.account",
                verbose_name="Conta prevista",
            ),
        ),
    ]
