# Generated by Django 6.0.5 on 2026-06-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_invoice_expected_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="installment_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Informe apenas quando a recorrência for Parcelado.",
                null=True,
                verbose_name="Quantidade de parcelas",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recurrence_interval",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Número do intervalo para gerar as próximas recorrências.",
                verbose_name="Intervalo de recorrência",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recurrence_interval_unit",
            field=models.CharField(
                choices=[("day", "Dias"), ("month", "Mes"), ("year", "Ano")],
                default="month",
                max_length=10,
                verbose_name="Unidade do intervalo",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("once", "Unica"),
                    ("fixed", "Fixa"),
                    ("monthly", "Mensal"),
                    ("quarterly", "Trimestral"),
                    ("yearly", "Anual"),
                    ("installment", "Parcelado"),
                ],
                default="once",
                max_length=20,
                verbose_name="Recorrência",
            ),
        ),
    ]
