# Generated by Django 6.0.5 on 2026-06-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0005_invoice_installment_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="nfse_error",
            field=models.TextField(blank=True, verbose_name="Erro NFS-e"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="nfse_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número NFS-e"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="nfse_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="NFS-e solicitada em"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="nfse_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nfse_pending", "Aguardando emissão"),
                    ("nfse_processing", "Emitindo..."),
                    ("nfse_issued", "NFS-e emitida"),
                    ("nfse_failed", "Falha na emissão"),
                ],
                max_length=20,
                null=True,
                verbose_name="Status NFS-e",
            ),
        ),
    ]
