# Generated by Django 6.0.2 on 2026-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('done', 'Finalizado')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluida em'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Concluida'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
