# Generated by Codex on 2026-03-24

from django.conf import settings
from django.db import migrations


DOMAIN_MODELS = (
    ("accounts", "Account"),
    ("categories", "Category"),
    ("transactions", "ClosedMonth"),
    ("transactions", "Transaction"),
    ("shopping", "ShoppingList"),
    ("shopping", "ShoppingItem"),
)


def build_tenant_name(user):
    first_name = (getattr(user, "first_name", "") or "").strip()
    if first_name:
        return f"{first_name} Workspace"

    username = (getattr(user, "username", "") or "").strip()
    if username:
        return f"{username} Workspace"

    return f"Cliente {user.pk}"


def create_default_tenants(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)
    Tenant = apps.get_model("tenants", "Tenant")
    TenantMembership = apps.get_model("tenants", "TenantMembership")

    tenant_ids_by_user = {}
    default_memberships = TenantMembership.objects.filter(is_default=True)
    for membership in default_memberships.iterator():
        tenant_ids_by_user[membership.user_id] = membership.tenant_id

    for user in User.objects.order_by("pk").iterator():
        tenant_id = tenant_ids_by_user.get(user.pk)
        if tenant_id is None:
            tenant = Tenant.objects.create(
                name=build_tenant_name(user),
                slug=f"tenant-{user.pk}",
                owner_id=user.pk,
                is_active=True,
            )
            TenantMembership.objects.create(
                tenant_id=tenant.pk,
                user_id=user.pk,
                role="owner",
                is_default=True,
            )
            tenant_id = tenant.pk
            tenant_ids_by_user[user.pk] = tenant_id

        for app_label, model_name in DOMAIN_MODELS:
            model = apps.get_model(app_label, model_name)
            model.objects.filter(user_id=user.pk, tenant_id__isnull=True).update(
                tenant_id=tenant_id
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        ("accounts", "0004_remove_account_unique_account_name_per_user_and_more"),
        ("categories", "0002_remove_category_unique_category_name_type_per_user_and_more"),
        ("transactions", "0010_remove_closedmonth_unique_closed_month_per_user_and_more"),
        ("shopping", "0004_remove_shoppinglist_unique_shopping_list_name_per_user_and_more"),
    ]

    operations = [
        migrations.RunPython(create_default_tenants, noop_reverse),
    ]
