# Generated by Django 6.0.5 on 2026-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_backfill_personal_tenants"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Cidade e UF"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="document",
            field=models.CharField(blank=True, max_length=20, verbose_name="CNPJ/CPF"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail comercial"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
    ]
