# Generated by Django 6.0.5 on 2026-06-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_address_tenant_city_tenant_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tenant_logos/",
                verbose_name="Logo da empresa",
            ),
        ),
    ]
