# Generated by Django 6.0.5 on 2026-06-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0004_tenant_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address_complement",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="address_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="Numero"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="district",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="postal_code",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="state",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Logradouro"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
    ]
