# Generated by Django 6.0.5 on 2026-06-23 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_tenant_address_complement_tenant_address_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NfseCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gov_br_cpf",
                    models.CharField(max_length=14, verbose_name="CPF gov.br"),
                ),
                (
                    "gov_br_password_enc",
                    models.TextField(verbose_name="Senha criptografada"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nfse_credential",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credencial NFS-e",
                "verbose_name_plural": "Credenciais NFS-e",
            },
        ),
    ]
